### PR TITLE
Remove overly old openbgpd versions

### PR DESCRIPTION
**Pull request by cjeker**
It is time to remove support for very old OpenBGPD versions and with that all the special handling needed.
OpenBGPD will support old versions for about a year but in -portable currently no stable branches are maintained.

There is no need to keep anything older than 7.0 especially since these versions are sometimes so limited that they wont work properly.

I tried to adapt the test suite but I can't run all tests so more may be broken.

### CODE REVIEW

**Comment by pierky** [comment]
That's a big one, thanks @cjeker for filing it!
I agree that we can drop the backflips done to support versions older than 7.0.
I'll take care of it ASAP and I'll complete the work you started here (if necessary).

**Comment by cjeker** [comment]
Thanks for taking care of this.

**Comment by pierky** [comment]
I spun up a new branch (which is based on the current development branch, [dev](https://github.com/pierky/arouteserver/tree/dev)), [cjeker-remove_overly_old_openbgpd_versions](https://github.com/pierky/arouteserver/tree/cjeker-remove_overly_old_openbgpd_versions); so far, I've reviewed your changes, which seem good, and I just posted a new commit, https://github.com/pierky/arouteserver/commit/1c3f609d6cfc34b3ed5f1e8f0a933a6bf7034528

    The `expires` was introduced only as part of 7.2:
    
    https://marc.info/?l=openbsd-announce&m=163239274430211&w=2
    
    So if the tool is run against a 7.0 or 7.1 it should not add the
    `expires` attribute to ROAs.

Am I saying the true there?

**Comment by pierky** [comment]
Deprecation of < 7.0 will be part of v1.20, which is currently going through the CI/CD pipeline and hopefully will be out in 1 hour or so from now.
Thanks for reporting it!

**Pull request merged**
